### ISSUE TITLE
a typo

### ISSUE THREAD

**Issue by leommxj** [N1ghtu/RWCTF6th-RIPTC#1]
Should be `6th` in README :)
> RIPTC is a hard (1 solve/ 2291 teams) realworld linux kernel challenge in Real World CTF 5th.

**Comment by nightuhu** [comment]
Fixed. Thanks！

**Comment by otodak** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
916983154, @BoCheung, @nknganda, @tangyinbo, @turingnixstyx, @owen800q, @ReDev1L, @0xACE3, @wjpsky, @osaka-sa-joho, @0xRake, @steal-7126, @wallanpsantos, @zhtnk, @tgntr, @strugglebak, @AlexRipoll, @tv1ktor, @OKTAYKIR, @stuartly, @97058234, @thatzprem, @JimboFromLimbo, @doganbolivar, @kunalgoyal9, @punitpratapsingh, @Akkabi, @Aakarshan-369, @laindream, @Sushruthan222, @Seank30, @Junying123, @mateuszkasprowicz, @Hz1234, @ninja-1337, @haiswang1989, @MelkorNemesis, @vonlooten, @rxldj5, @moises2406, @ejacky, @hweawer, @dunnostrong, @overphoenix, @thedlearner, @hung-ngm, @luis-herasme, @fariharana-1, @natalyakripto, @upstate-online

**Comment by byungster** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
devdot4, @Ce1ling, @Demul1, @leybzon, @wilsonfonseca, @RestiveSole267, @dewedeth, @jasonzou, @essldd, @lowitea, @Tweetus-Bot, @belov38, @adubkov, @IdealisticINTJ, @jpalvarezl, @anthedung, @AmrAlaaYassen, @crueber, @Gazzuye12, @derFBeste, @saadqbal, @kenneth, @ajay-a1, @yxliang01, @eddyso05, @aiolos404, @TheOfficialDM, @fabius8, @hqtoan94, @beppe9000, @ToJen, @makesource, @AjayRajkumar, @luckyJing6, @bumi, @ben622, @jujutsu764e, @lennonjesus, @zoro9483, @ovx, @daveleee, @Anson-2022, @leverly, @dantehemerson, @ebrahimkhodadadi, @mdsalik7, @tsmart30, @VisH317, @andreis, @likaihere
